Learning Numpy

In [22]:
import numpy as np
import os
array = np.array([1,2,3])
array1 = np.array([[3,6],[4,7]])
array2 = np.array([[1,3,5],[9,10,5]])
array, array1
print("array type", type(array1))
print("type of elements", array1.dtype)

print("dim = ", array1.ndim)
print("shape = ", array.shape)

zeroArray = np.zeros((3,4), dtype='uint8')
print(zeroArray)

constArray = np.full((4,4),8, dtype = 'float16')
print(constArray)

randomarray = np.random.randint(50,100, size=(4,4))
print(randomarray)

array type <class 'numpy.ndarray'>
type of elements int64
dim =  2
shape =  (3,)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]
[[79 57 72 83]
 [80 58 63 57]
 [96 51 91 99]
 [93 75 80 53]]


Operations and Data Types

In [23]:
array3 = array+array1
print(array3)
sum = np.add(array1, array3)
print(sum)
array3 = array1**2
print(array3)
sqrArray3 = np.sqrt(array3)
print(sqrArray3.dtype)

array4 = np.array([2,3,4],[5,6,7],[8,9,10])
print(array4)
Trans_array = array4.T
print(Trans_array)

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

Indexing and slicing

In [24]:
arrayLine = np.linspace(0,10,21)
print(arrayLine)

arrayRange = np.arange(10,200,5)
print(arrayRange)
print(arrayRange[30:50:1])

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]
[160 165 170 175 180 185 190 195]
